name: strapi

type: "nodejs:18"  # Utilisation de Node.js version 16
disk: 2048

build:
    flavor: "none"

dependencies:
    nodejs:
        "@strapi/strapi": "^4.0.0"

mounts:
    '/srv/app': 'shared:files'  # Garde les fichiers persistants dans le dossier app

web:
    commands:
        start: npm start
    #locations:
    #    "/":
    #        root: "public"
    #        passthru: true
    #    "/admin":
    #        root: "public"
    #        passthru: true
    #    "/uploads":
    #        root: "public"
    #        allow: true

hooks:
    build:
        npm install

relationships:
    database: "postgresql:postgresql"  # Relation avec la base de données PostgreSQL
    # cache: "cache:redis"       # Relation avec Redis pour la gestion du cache

variables:
    env:
        NODE_ENV: "production"
        APP_KEYS: ${APP_KEYS}
        ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
        JWT_SECRET: ${JWT_SECRET}
        API_TOKEN_SALT: ${API_TOKEN_SALT}
